### ISSUE TITLE
Define commit standards

### ISSUE THREAD

**Issue by kalilistic** [the-convocation/venat#6]
Any standards to keep things consistent and let us generate change logs easier?

https://www.conventionalcommits.org/en/v1.0.0/
https://github.com/webiny/action-conventional-commits

**Comment by kalilistic** [comment]
Everyone agreed to try out CC and see how it goes.

**Comment by ArcaneDisgea** [comment]
Yeah, I am down with CC. As long as it's consistent I think the benefits of automated changelogs and such will be worth it.
