### ISSUE TITLE
Implement module for Kaiyoko's fashion report

### ISSUE THREAD

**Issue by karashiiro** [the-convocation/venat#71]
**Is your feature request related to a problem? Please describe.**
No fashion module.

**Describe the solution you'd like**
Fashion module.

**Describe alternatives you've considered**
No

**Additional context**
I want MGP

**Comment by ArcaneDisgea** [comment]
We need more details unfortunately. It's very hard to implement a feature without a clear direction in what you want. Would this fashion module tell you how to dress or just rate your outfit?

**Comment by karashiiro** [comment]
I want it to tell me how to get MGP

**Comment by kalilistic** [comment]
OCR?

**Comment by karashiiro** [comment]
[OCR.](https://github.com/naptha/tesseract.js)

**Comment by karashiiro** [comment]
Closing in favor of #100
