### ISSUE TITLE
Rename modules to plugins

### ISSUE THREAD

**Issue by kalilistic** [the-convocation/venat#81]
Avoid confusing ourselves.

**Comment by MKhayle** [comment]
@ackwell sent this on discord : 
![image](https://user-images.githubusercontent.com/4359469/169433463-8245cce1-504d-4a9a-a9a1-5ea10ebf8b24.png)

Thoughts ? 

Should we rename the "non-core module" label to "plugins" ?

**Comment by MKhayle** [comment]
I changed the name for the issues to "plugin" for now, we can discuss about what are modules inside those in said issues if it is needed at some point

**Comment by kalilistic** [comment]
Closed this early, should be some code changes here too I'd expect.
