### ISSUE TITLE
Implement a non-Core FFXIV Weather Plugin

### ISSUE THREAD

**Issue by MKhayle** [the-convocation/venat#87]
### Is your feature request related to a problem? Please describe.

We require a Weather plugin for potential dependencies from other plugins.

### Describe the solution you would like.

We need a Weather Plugin with methods to get weather data for any given zone at any given time. 
May require #74 first for zones handling and weather types first-hand. Would be required for #78.

That may potentially include a command for users : `/weather` `Upper la Noscea` `now` but that may be messy because of localization and/or time. Maybe we could, however, use [Discord Select Menus](https://github.com/the-convocation/venat/issues/78) to allow the user to choose from options we would set ourselves and avoid confusion / wrong options input but that would make the overall command use slower.

Pinging @karashiiro here as I've read somewhere that kara had a weather lib already.

### Describe alternatives you've considered.

Make ingame bots in each zone in the game where it could be talking to Skywatcher NPCs every 2 hours, then proceed to screenshot the NPC's text, OCR it and send it to a core API. May cause insane devs to become even less sane.

**Comment by karashiiro** [comment]
I have libs for C# and Python, JS/TS is [this person's](https://github.com/eorzea-weather/node-eorzea-weather).

**Comment by karashiiro** [comment]
Though honestly, that one's a bit wack since all of the game data has been hand-translated into code. It doesn't have weather rates for any non-field zones, either (not that anyone really cares about the weather in P4). Still, for the typical zones it works.

**Comment by MKhayle** [comment]
I can think of Diadem's and Bozja/Zadnor's zones as important non-typical zones where it could be required for special events happening during specific weathers and it looks like [those zones are covered](https://github.com/eorzea-weather/node-eorzea-weather/blob/main/src/zones.ts). Is there any specific zone we could be missing out ?

**Comment by karashiiro** [comment]
Oh, it also only supports English and Japanese, somehow I never noticed that, before.

**Comment by karashiiro** [comment]
I'll add that I am extremely biased on the design of anything that can use game data (directly or through a dump), but doesn't.

**Comment by MKhayle** [comment]
To be honest I'd advise against relying on external tools if we can avoid it for the reasons you mentioned earlier and because we can cover those needs by ourselves. If it also lacks DE/FR data, then I'm all in for some homebrewed solution to deal with that.

**Comment by karashiiro** [comment]
Perfect, [because](https://github.com/karashiiro/ffxivweather-py/blob/master/ffxivweather/forecaster.py) it'd be [trivial](https://github.com/karashiiro/FFXIVWeather.Lumina/blob/master/FFXIVWeather.Lumina/FFXIVWeatherLuminaService.cs).

**Comment by karashiiro** [comment]
Alright, I'm taking this. I'll implement it completely within venat rather than as a library because it'll be very small. For now, it'll just use XIVAPI until we get around to setting up #74.
